version: '3.9'

services:
  app:
    image: node:21-bookworm
    container_name: backend-chongapi
    working_dir: /app
    volumes:
      - .:/app:cache
    environment:
      - NODE_ENV=development
    ports:
      - "4447:4447"
    command: npm run start:dev
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15-bookworm
    container_name: postgres_db
    mem_limit: 1536MB
    mem_reservation: 1G
    environment:
      POSTGRES_DB: chongapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/15/data
    command: "postgres -c 'max_connections=500'"

networks:
  backend:
    name: backend

volumes:
  postgres_data: {}